project:
  type: website
  output-dir: docs

website:
  title: "Empirical species size distribution"
  sidebar:
    search: false
    style: "floating"
    contents:
      - href: index.qmd
        text: Background
      - href: data_cleaning.qmd
        text: Data cleaning
      - href: simple_system.qmd
        text: Simple system
      - href: shane_jervisbay.qmd
        text: Jervis Bay (Shane)
      - href: gridcell.qmd
        text: Gridcell (single species)
      - href: universal.qmd
        text: Universal body size

format:
  html:
    theme: cosmo
    toc: true